#!/usr/bin/env python3
"""Render grid + landing pages from templates/ + tracks/.

Usage:
  python render.py                # render everything
  python render.py rhymes papa-liedjes  # render named grids only
"""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).parent

# Grid pages = anything that lists tracks/songs/stories with tile playback.
# Each entry: tracks/<name>.json must define its own metadata + tracks array.
# out_dir is the relative path under repo root where files are written.
GRIDS = {
    "rhymes":         {"tracks": "tracks/rhymes.json",         "out_dir": "rhymes"},
    "eendjes":        {"tracks": "tracks/eendjes.json",        "out_dir": "eendjes"},
    "papa-liedjes":   {"tracks": "tracks/papa-liedjes.json",   "out_dir": "papa/liedjes"},
    "papa-verhalen":  {"tracks": "tracks/papa-verhalen.json",  "out_dir": "papa/verhalen"},
    "mama-liedjes":   {"tracks": "tracks/mama-liedjes.json",   "out_dir": "mama/liedjes"},
    "mama-verhalen":  {"tracks": "tracks/mama-verhalen.json",  "out_dir": "mama/verhalen"},
    "klas-liedjes":   {"tracks": "tracks/klas-liedjes.json",   "out_dir": "klas/liedjes"},
    "klas-verhalen":  {"tracks": "tracks/klas-verhalen.json",  "out_dir": "klas/verhalen"},
}

# Landing pages = 3-category tile pages per language.
LANDINGS = {
    "mama": {"out_dir": "mama", "lang": "fr", "photo": "/liedjes/home/mama.jpg", "title_fallback": "Mama"},
    "papa": {"out_dir": "papa", "lang": "nl", "photo": "/liedjes/home/papa.jpg", "title_fallback": "Papa"},
    "klas": {"out_dir": "klas", "lang": "en", "photo": "/liedjes/home/klas.jpg", "title_fallback": "Klas"},
}


def render_grid(name, config):
    tracks_path = ROOT / config["tracks"]
    if not tracks_path.exists():
        print(f"[skip] {name}: {tracks_path} not found")
        return
    spec = json.loads(tracks_path.read_text())
    out_dir = ROOT / config["out_dir"]
    out_dir.mkdir(parents=True, exist_ok=True)

    # Render grid.html
    template = (ROOT / "templates/grid.html").read_text()
    html = (template
        .replace("__GRID_TITLE__",     spec["title"])
        .replace("__HTML_LANG__",      spec["lang"])
        .replace("__PARENT_PHOTO__",   spec["parent_photo"])
        .replace("__PARENT_HREF__",    spec.get("parent_href", "/liedjes/"))
        .replace("__APP_VERSION__",    spec["app_version"])
        .replace("__STORAGE_PREFIX__", spec["storage_prefix"])
        .replace("__TRACKS_JSON__",    json.dumps(spec["tracks"], ensure_ascii=False))
        .replace("__SEED_ORDER__",     json.dumps(spec.get("seed_order", [])))
    )
    (out_dir / "index.html").write_text(html, encoding="utf-8")

    # Render service-worker.js
    sw_template = (ROOT / "templates/service-worker.js").read_text()
    sw = (sw_template
        .replace("__CACHE_NAME__",     spec["cache_name"])
        .replace("__MP3_CACHE_NAME__", spec["mp3_cache_name"])
    )
    (out_dir / "service-worker.js").write_text(sw, encoding="utf-8")

    # Write popularity.json with the seed
    (out_dir / "popularity.json").write_text(
        json.dumps(
            {"seed": spec.get("seed_order", []), "note": f"Generated by render.py for {name}"},
            indent=2,
        ),
        encoding="utf-8",
    )

    # Write manifest.json
    manifest = {
        "name": spec.get("manifest_name", spec["title"]),
        "short_name": spec.get("manifest_name", spec["title"]),
        "start_url": "./",
        "display": "standalone",
        "background_color": "#fff7e6",
        "theme_color": "#fff7e6",
        "icons": [
            {"src": "icon-192.png", "sizes": "192x192", "type": "image/png"},
            {"src": "icon-512.png", "sizes": "512x512", "type": "image/png"},
        ],
    }
    (out_dir / "manifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")

    print(f"[ok]  {name} → {config['out_dir']}/  ({len(spec['tracks'])} tracks)")


def render_landing(name, config):
    template = (ROOT / "templates/landing.html").read_text()
    out_dir = ROOT / config["out_dir"]
    out_dir.mkdir(parents=True, exist_ok=True)

    html = (template
        .replace("__HTML_LANG__",      config["lang"])
        .replace("__PARENT_PHOTO__",   config["photo"])
        .replace("__TITLE_FALLBACK__", config["title_fallback"])
        .replace("__LANG_PATH__",      name)
    )
    (out_dir / "index.html").write_text(html, encoding="utf-8")
    print(f"[ok]  landing {name} → {config['out_dir']}/")


def main():
    selected = set(sys.argv[1:])
    for name, cfg in GRIDS.items():
        if not selected or name in selected:
            render_grid(name, cfg)
    for name, cfg in LANDINGS.items():
        if not selected or name in selected:
            render_landing(name, cfg)


if __name__ == "__main__":
    main()
