#!/usr/bin/env python3
"""Render grid + taal pages from templates/ + tracks/.

Usage:
  python render.py                # render everything
  python render.py rhymes klas    # render named grids/talen only
"""

import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).parent


def content_hash(*parts) -> str:
    h = hashlib.sha256()
    for p in parts:
        if isinstance(p, (dict, list)):
            h.update(json.dumps(p, sort_keys=True, ensure_ascii=False).encode())
        elif isinstance(p, str):
            h.update(p.encode())
        elif isinstance(p, bytes):
            h.update(p)
        h.update(b"\0")
    return h.hexdigest()[:8]

# Grid pages = standalone playback grids (rhymes, eendjes).
GRIDS = {
    "rhymes":  {"tracks": "tracks/rhymes.json",  "out_dir": "rhymes"},
    "eendjes": {"tracks": "tracks/eendjes.json",  "out_dir": "eendjes"},
}

# Section header labels per language.
SECTION_LABELS = {
    "nl": {"boeken": "Boeken", "liedjes": "Liedjes", "verhalen": "Verhalen"},
    "fr": {"boeken": "Livres", "liedjes": "Chansons", "verhalen": "Histoires"},
    "en": {"boeken": "Books",  "liedjes": "Songs",    "verhalen": "Stories"},
}

# Taal pages = single multi-section pages (boeken / liedjes / verhalen stacked).
TALEN = {
    "mama": {
        "out_dir": "mama",
        "lang": "fr",
        "parent_photo": "/liedjes/home/mama.jpg",
        "parent_href": "/liedjes/",
        "title_fallback": "Mama",
        "storage_prefix": "mama",
        "manifest_name": "Mama",
        "sections": ["boeken", "liedjes", "verhalen"],
    },
    "papa": {
        "out_dir": "papa",
        "lang": "nl",
        "parent_photo": "/liedjes/home/papa.jpg",
        "parent_href": "/liedjes/",
        "title_fallback": "Papa",
        "storage_prefix": "papa",
        "manifest_name": "Papa",
        "sections": ["boeken", "liedjes", "verhalen"],
    },
    "klas": {
        "out_dir": "klas",
        "lang": "en",
        "parent_photo": "/liedjes/home/klas.jpg",
        "parent_href": "/liedjes/",
        "title_fallback": "Klas",
        "storage_prefix": "klas",
        "manifest_name": "Klas",
        "sections": ["boeken", "liedjes", "verhalen"],
    },
}


def render_grid(name, config):
    tracks_path = ROOT / config["tracks"]
    if not tracks_path.exists():
        print(f"[skip] {name}: {tracks_path} not found")
        return
    spec = json.loads(tracks_path.read_text())
    out_dir = ROOT / config["out_dir"]
    out_dir.mkdir(parents=True, exist_ok=True)

    # Render grid.html
    template = (ROOT / "templates/grid.html").read_text()
    html = (template
        .replace("__GRID_TITLE__",     spec["title"])
        .replace("__HTML_LANG__",      spec["lang"])
        .replace("__PARENT_PHOTO__",   spec["parent_photo"])
        .replace("__PARENT_HREF__",    spec.get("parent_href", "/liedjes/"))
        .replace("__ACTIVE_TAAL__",    spec.get("active_taal", ""))
        .replace("__APP_VERSION__",    spec["app_version"])
        .replace("__STORAGE_PREFIX__", spec["storage_prefix"])
        .replace("__TRACKS_JSON__",    json.dumps(spec["tracks"], ensure_ascii=False))
        .replace("__SEED_ORDER__",     json.dumps(spec.get("seed_order", [])))
    )
    (out_dir / "index.html").write_text(html, encoding="utf-8")

    # Render service-worker.js
    sw_template = (ROOT / "templates/service-worker.js").read_text()
    sw = (sw_template
        .replace("__CACHE_NAME__",     spec["cache_name"])
        .replace("__MP3_CACHE_NAME__", spec["mp3_cache_name"])
    )
    (out_dir / "service-worker.js").write_text(sw, encoding="utf-8")

    # Write popularity.json with the seed
    (out_dir / "popularity.json").write_text(
        json.dumps(
            {"seed": spec.get("seed_order", []), "note": f"Generated by render.py for {name}"},
            indent=2,
        ),
        encoding="utf-8",
    )

    # Write manifest.json
    manifest = {
        "name": spec.get("manifest_name", spec["title"]),
        "short_name": spec.get("manifest_name", spec["title"]),
        "start_url": "./",
        "display": "standalone",
        "background_color": "#fff7e6",
        "theme_color": "#fff7e6",
        "icons": [
            {"src": "icon-192.png", "sizes": "192x192", "type": "image/png"},
            {"src": "icon-512.png", "sizes": "512x512", "type": "image/png"},
        ],
    }
    (out_dir / "manifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")

    print(f"[ok]  {name} → {config['out_dir']}/  ({len(spec['tracks'])} tracks)")


def render_taal(name, config):
    template = (ROOT / "templates/taal.html").read_text()
    out_dir = ROOT / config["out_dir"]
    out_dir.mkdir(parents=True, exist_ok=True)

    # Collect tracks from all sections, tagged with _section
    all_tracks = []
    for section in config["sections"]:
        path = ROOT / f"tracks/{name}-{section}.json"
        if not path.exists():
            continue
        data = json.loads(path.read_text())
        for t in data.get("tracks", []):
            t["_section"] = section
            all_tracks.append(t)

    # Seed order: first 5 tracks across all sections (audio tiles only)
    audio_keys = [f"{t['_section']}:{t['n']}" for t in all_tracks if t.get("audio")][:5]

    labels = SECTION_LABELS.get(config["lang"], SECTION_LABELS["nl"])

    # Auto-derive cache versions from a content hash so any content/template
    # change automatically invalidates PWA caches on next page load.
    sw_template = (ROOT / "templates/service-worker.js").read_text()
    ver = content_hash(all_tracks, template, sw_template, config["lang"], labels)
    app_version = f"{name}-{ver}"
    cache_name = f"{name}-{ver}"
    mp3_cache_name = f"{name}-mp3-{ver}"

    html = (template
        .replace("__HTML_LANG__",       config["lang"])
        .replace("__PARENT_PHOTO__",    config["parent_photo"])
        .replace("__PARENT_HREF__",     config["parent_href"])
        .replace("__TITLE_FALLBACK__",  config["title_fallback"])
        .replace("__APP_VERSION__",     app_version)
        .replace("__STORAGE_PREFIX__",  config["storage_prefix"])
        .replace("__LABEL_BOEKEN__",    labels["boeken"])
        .replace("__LABEL_LIEDJES__",   labels["liedjes"])
        .replace("__LABEL_VERHALEN__",  labels["verhalen"])
        .replace("__ALL_TRACKS_JSON__", json.dumps(all_tracks, ensure_ascii=False))
        .replace("__SEED_ORDER__",      json.dumps(audio_keys))
    )
    (out_dir / "index.html").write_text(html, encoding="utf-8")

    # Service worker (reuse existing template)
    sw = (sw_template
        .replace("__CACHE_NAME__",     cache_name)
        .replace("__MP3_CACHE_NAME__", mp3_cache_name)
    )
    (out_dir / "service-worker.js").write_text(sw, encoding="utf-8")

    # popularity.json (seed = audio_keys joined as "section:n" strings)
    (out_dir / "popularity.json").write_text(
        json.dumps({"seed": audio_keys, "note": f"Generated by render.py for taal {name}"}, indent=2),
        encoding="utf-8",
    )

    # manifest.json
    manifest = {
        "name": config["manifest_name"],
        "short_name": config["manifest_name"],
        "start_url": "./",
        "display": "standalone",
        "background_color": "#fff7e6",
        "theme_color": "#fff7e6",
        "icons": [
            {"src": "icon-192.png", "sizes": "192x192", "type": "image/png"},
            {"src": "icon-512.png", "sizes": "512x512", "type": "image/png"},
        ],
    }
    (out_dir / "manifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")

    non_empty = len([
        s for s in config["sections"]
        if (ROOT / f"tracks/{name}-{s}.json").exists()
        and json.loads((ROOT / f"tracks/{name}-{s}.json").read_text()).get("tracks")
    ])
    print(f"[ok]  taal {name} → {config['out_dir']}/  ({len(all_tracks)} tracks across {non_empty} non-empty sections)")


def main():
    selected = set(sys.argv[1:])
    for name, cfg in GRIDS.items():
        if not selected or name in selected:
            render_grid(name, cfg)
    for name, cfg in TALEN.items():
        if not selected or name in selected:
            render_taal(name, cfg)


if __name__ == "__main__":
    main()
