// Generated by render.py from templates/service-worker.js
// Cache names per-grid so multiple grids on the same origin don't collide.

const CORE_CACHE = "klas-v3";
const MP3_CACHE  = "klas-mp3-v3";

const CORE = [
  "./",
  "./index.html",
  "./manifest.json",
  "./apple-touch-icon.png",
  "./icon-192.png",
  "./icon-512.png",
  "./favicon-32.png",
  "./popularity.json",
];

self.addEventListener("install", e => {
  e.waitUntil(caches.open(CORE_CACHE).then(c => c.addAll(CORE)).catch(() => {}));
  self.skipWaiting();
});

self.addEventListener("activate", e => {
  e.waitUntil(
    caches.keys().then(keys =>
      Promise.all(keys.filter(k => k !== CORE_CACHE && k !== MP3_CACHE).map(k => caches.delete(k)))
    ).then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", e => {
  const url = new URL(e.request.url);
  if (url.origin !== self.location.origin) return;

  const isHTML = e.request.mode === "navigate"
              || e.request.destination === "document"
              || url.pathname.endsWith("/")
              || url.pathname.endsWith(".html");

  if (isHTML) {
    e.respondWith(
      fetch(e.request).then(resp => {
        const copy = resp.clone();
        caches.open(CORE_CACHE).then(c => c.put(e.request, copy)).catch(() => {});
        return resp;
      }).catch(() => caches.match(e.request).then(r => r || caches.match("./")))
    );
    return;
  }

  e.respondWith(
    caches.match(e.request).then(cached => {
      const fetchAndCache = fetch(e.request).then(resp => {
        if (resp && resp.status === 200) {
          const copy = resp.clone();
          caches.open(CORE_CACHE).then(c => c.put(e.request, copy)).catch(() => {});
        }
        return resp;
      }).catch(() => cached);
      return cached || fetchAndCache;
    })
  );
});

let prefetching = false;
self.addEventListener("message", async e => {
  const msg = e.data;
  if (!msg || msg.type !== "prefetch-mp3s" || !Array.isArray(msg.urls)) return;
  if (prefetching) return;
  prefetching = true;

  const cache = await caches.open(MP3_CACHE);
  const total = msg.urls.length;
  let done = 0, cached = 0;
  const post = (payload) => { if (e.source) e.source.postMessage(payload); };

  const CONCURRENCY = 4;
  let cursor = 0;
  async function worker() {
    while (cursor < total) {
      const idx = cursor++;
      const u = msg.urls[idx];
      try {
        const req = new Request(u, { mode: "no-cors", credentials: "omit" });
        const existing = await cache.match(req, { ignoreVary: true });
        if (!existing) { const resp = await fetch(req); await cache.put(req, resp); }
        cached++;
      } catch {}
      done++;
      post({ type: "prefetch-progress", done, total });
    }
  }
  await Promise.all(Array.from({ length: Math.min(CONCURRENCY, total) }, worker));
  prefetching = false;
  post({ type: "prefetch-done", cached, total });
});
